# Generated by Django 6.0.3 on 2026-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
