# Generated by Django 6.0.3 on 2026-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_providerprofile_profile_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
