# Generated by Django 6.0.3 on 2026-05-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_providerprofile_availability_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='bank_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identity_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
