CATEGORY_SERVICE_CATALOG = {
    "HOME SERVICES": {
        "price_start": 399,
        "price_step": 50,
        "description_template": "Professional {title_lower} for homes, apartments, and offices with verified technicians, basic tools, and a clean finish.",
        "services": [
            "Plumbing Repair",
            "Bathroom Plumbing Installation",
            "Kitchen Sink Repair",
            "Water Leakage Fix",
            "Tap Installation",
            "Pipe Replacement",
            "Motor Repair",
            "Water Tank Cleaning",
            "Electric Wiring Repair",
            "Switchboard Repair",
            "Fan Installation",
            "Light Installation",
            "Door Repair",
            "Window Repair",
            "Furniture Repair",
            "Carpentry Work",
            "Home Painting",
            "Wall Repair",
            "Curtain Installation",
            "Drill and Wall Mounting",
        ],
    },
    "CLEANING SERVICES": {
        "price_start": 699,
        "price_step": 75,
        "description_template": "Reliable {title_lower} using safe cleaning materials, trained staff, and flexible scheduling for residential and office spaces.",
        "services": [
            "Home Deep Cleaning",
            "Bathroom Cleaning",
            "Kitchen Cleaning",
            "Sofa Cleaning",
            "Carpet Cleaning",
            "Mattress Cleaning",
            "Office Cleaning",
            "Window Cleaning",
            "Floor Cleaning",
            "Water Tank Cleaning",
            "Move-in Cleaning",
            "Move-out Cleaning",
            "Balcony Cleaning",
            "Dust Removal Service",
            "Disinfection Service",
            "Apartment Cleaning",
            "Villa Cleaning",
            "Post Construction Cleaning",
            "Chair Cleaning",
            "Glass Cleaning",
        ],
    },
    "TECHNICAL SERVICES": {
        "price_start": 499,
        "price_step": 100,
        "description_template": "Doorstep {title_lower} with diagnostics, repairs, installation support, and post-service testing by skilled technicians.",
        "services": [
            "Laptop Repair",
            "Desktop Repair",
            "Printer Repair",
            "Mobile Repair",
            "Software Installation",
            "Windows Installation",
            "Virus Removal",
            "Data Recovery",
            "WiFi Setup",
            "Router Installation",
            "Internet Troubleshooting",
            "Email Setup",
            "Cloud Backup Setup",
            "Hardware Upgrade",
            "Keyboard Repair",
            "Screen Replacement",
            "PC Cleaning",
            "CCTV Software Setup",
            "Operating System Upgrade",
            "Driver Installation",
        ],
    },
    "DELIVERY & ERRANDS": {
        "price_start": 99,
        "price_step": 25,
        "description_template": "Fast {title_lower} with careful handling, real-time updates, and doorstep support for everyday tasks.",
        "services": [
            "Grocery Delivery",
            "Medicine Delivery",
            "Food Pickup",
            "Parcel Delivery",
            "Document Delivery",
            "Courier Pickup",
            "Laundry Pickup",
            "Bill Payment Service",
            "Bank Work Assistance",
            "Shopping Assistance",
            "Gift Delivery",
            "Flower Delivery",
            "Pickup from Store",
            "Drop to Office",
            "Airport Parcel Delivery",
            "Urgent Delivery",
            "Same Day Delivery",
            "Package Return Service",
            "Home Essentials Delivery",
            "Pet Food Delivery",
        ],
    },
    "EDUCATION": {
        "price_start": 399,
        "price_step": 80,
        "description_template": "Structured {title_lower} with experienced tutors, practical lessons, and progress tracking for learners of all levels.",
        "services": [
            "Home Tutor Math",
            "Home Tutor Science",
            "Home Tutor English",
            "Online Tutor",
            "Spoken English Training",
            "Programming Classes",
            "Python Classes",
            "Java Classes",
            "Web Development Training",
            "Data Science Coaching",
            "Music Classes",
            "Dance Classes",
            "Drawing Classes",
            "Yoga Training",
            "Exam Preparation Coaching",
            "NEET Coaching",
            "JEE Coaching",
            "Soft Skills Training",
            "Public Speaking Training",
            "Computer Basics Training",
        ],
    },
    "BEAUTY & SALON": {
        "price_start": 299,
        "price_step": 60,
        "description_template": "Salon-quality {title_lower} at home with hygienic tools, professional care, and flexible time slots.",
        "services": [
            "Haircut at Home",
            "Hair Styling",
            "Hair Coloring",
            "Facial Service",
            "Bridal Makeup",
            "Party Makeup",
            "Manicure",
            "Pedicure",
            "Hair Spa",
            "Waxing Service",
            "Threading Service",
            "Eyebrow Shaping",
            "Skin Treatment",
            "Body Polishing",
            "Mehendi Service",
            "Nail Art",
            "Hair Straightening",
            "Hair Smoothening",
            "Keratin Treatment",
            "Beard Grooming",
        ],
    },
    "FITNESS": {
        "price_start": 699,
        "price_step": 100,
        "description_template": "Personalized {title_lower} with goal-based plans, certified guidance, and routine tracking for measurable progress.",
        "services": [
            "Personal Trainer",
            "Yoga Trainer",
            "Weight Loss Coach",
            "Diet Planning",
            "Gym Trainer",
            "Home Workout Trainer",
            "Meditation Trainer",
            "Zumba Trainer",
            "Cardio Trainer",
            "Strength Trainer",
            "Bodybuilding Coach",
            "Online Fitness Coaching",
            "Sports Fitness Training",
            "Running Coach",
            "Flexibility Training",
            "Muscle Gain Training",
            "Rehabilitation Training",
            "CrossFit Trainer",
            "Pilates Trainer",
            "Athletic Training",
        ],
    },
    "EVENT SERVICES": {
        "price_start": 1499,
        "price_step": 250,
        "description_template": "Reliable {title_lower} for birthdays, weddings, and corporate events with smooth on-ground coordination.",
        "services": [
            "Wedding Photographer",
            "Event Photographer",
            "Videographer",
            "DJ Service",
            "Event Decoration",
            "Birthday Planner",
            "Wedding Planner",
            "Catering Service",
            "Stage Decoration",
            "Lighting Setup",
            "Sound System Setup",
            "Anchor Service",
            "Party Organizer",
            "Balloon Decoration",
            "Corporate Event Planner",
            "Conference Organizer",
            "Wedding Makeup Artist",
            "Food Catering",
            "Photo Booth Setup",
            "Invitation Design",
        ],
    },
    "PERSONAL CARE": {
        "price_start": 599,
        "price_step": 90,
        "description_template": "Compassionate {title_lower} with safety-first support, flexible visits, and dependable daily assistance.",
        "services": [
            "Elderly Care",
            "Babysitting",
            "Nursing Care",
            "Physiotherapy",
            "Home Massage",
            "Patient Care",
            "Post Surgery Care",
            "Child Care",
            "Caretaker Service",
            "Mental Wellness Support",
            "Home Nurse Visit",
            "Health Monitoring",
            "Diet Consultation",
            "Personal Assistant",
            "Companion Service",
            "Medical Assistance",
            "Disability Care",
            "Home Doctor Visit",
            "Stress Therapy",
            "Sleep Therapy",
        ],
    },
    "PET SERVICES": {
        "price_start": 399,
        "price_step": 75,
        "description_template": "Professional {title_lower} with pet-friendly handling, hygiene, and care-focused service at your convenience.",
        "services": [
            "Pet Grooming",
            "Dog Walking",
            "Pet Sitting",
            "Veterinary Visit",
            "Pet Training",
            "Pet Bathing",
            "Pet Hair Trimming",
            "Pet Nail Cutting",
            "Pet Health Check",
            "Pet Boarding",
            "Pet Daycare",
            "Pet Vaccination",
            "Pet Diet Consultation",
            "Dog Trainer",
            "Cat Grooming",
            "Pet Transportation",
            "Pet Massage",
            "Pet Medical Assistance",
            "Pet Behavior Training",
            "Pet Exercise Training",
        ],
    },
    "PROFESSIONAL SERVICES": {
        "price_start": 499,
        "price_step": 120,
        "description_template": "Expert {title_lower} for individuals and businesses with transparent guidance, compliance support, and fast turnaround.",
        "services": [
            "Accountant Consultation",
            "Tax Filing Service",
            "Legal Advice",
            "Business Registration",
            "Trademark Registration",
            "Insurance Consultation",
            "Financial Planning",
            "Investment Advice",
            "Career Counseling",
            "Resume Writing",
            "Interview Coaching",
            "Business Consulting",
            "Startup Consulting",
            "Digital Marketing Consulting",
            "SEO Consulting",
            "HR Consulting",
            "GST Registration",
            "Company Formation",
            "Document Verification",
            "Contract Drafting",
        ],
    },
    "ODD JOBS": {
        "price_start": 299,
        "price_step": 50,
        "description_template": "Convenient {title_lower} for small home tasks, installation work, and quick fixes completed neatly.",
        "services": [
            "Furniture Assembly",
            "Packing Service",
            "Moving Assistance",
            "House Shifting Help",
            "Gardening Service",
            "Plant Care",
            "Wall Mount Installation",
            "Minor Repair Service",
            "Handyman Service",
            "Home Setup Help",
            "TV Installation",
            "Mirror Installation",
            "Shelf Installation",
            "Bed Assembly",
            "Office Setup Help",
            "Chair Repair",
            "Small Electrical Fix",
            "Basic Plumbing Fix",
            "Home Organization",
            "Storage Arrangement",
        ],
    },
    "AUTOMOBILE": {
        "price_start": 399,
        "price_step": 90,
        "description_template": "Professional {title_lower} for cars and two-wheelers with inspection, repair support, and dependable doorstep service.",
        "services": [
            "Car Repair",
            "Car Wash",
            "Bike Servicing",
            "Car Interior Detailing",
            "Wheel Alignment",
            "Battery Check",
            "Tyre Puncture Repair",
            "AC Gas Refill",
            "Engine Diagnosis",
            "Oil Change",
            "Chain Lubrication",
            "Clutch Service",
            "Brake Check",
            "Headlight Repair",
            "Dashboard Cleaning",
            "Seat Cover Installation",
            "Alloy Wheel Cleaning",
            "Parking Sensor Installation",
            "Car Polishing",
            "Roadside Assistance",
        ],
    },
    "FOOD SERVICES": {
        "price_start": 249,
        "price_step": 40,
        "description_template": "Fresh {title_lower} for homes, offices, and small events with custom menu options and timely delivery.",
        "services": [
            "Home Chef Meal Service",
            "Catering For Small Events",
            "Tiffin Service",
            "Lunch Box Delivery",
            "Meal Prep Service",
            "Office Lunch Catering",
            "Party Food Catering",
            "Birthday Cake Delivery",
            "Healthy Meal Subscription",
            "Vegetarian Meal Service",
            "Non Vegetarian Meal Service",
            "Breakfast Delivery",
            "Corporate Catering",
            "Live Food Counter",
            "Snack Box Service",
            "Custom Menu Planning",
            "Traditional Meal Catering",
            "Sweet Box Delivery",
            "Event Snack Counter",
            "Family Dinner Catering",
        ],
    },
}
