# Generated by Django 6.0.3 on 2026-04-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_address_booking_area_booking_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='area',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='locality',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('phonepe', 'PhonePe'), ('googlepay', 'Google Pay'), ('razorpay', 'Razorpay'), ('cash', 'Cash on Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20),
        ),
    ]
