# Generated by Django 6.0.3 on 2026-06-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('CONFIRMED', 'Confirmed'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed'), ('PAYMENT_VERIFICATION_PENDING', 'Payment Verification Pending'), ('PAYMENT_REJECTED', 'Payment Rejected')], default='PENDING', max_length=50),
        ),
    ]
