# Generated by Django 6.0.3 on 2026-04-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_IN_PROGRESS', 'Booking In Progress'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('PAYMENT_SUCCESS', 'Payment Success'), ('REFUND_INITIATED', 'Refund Initiated'), ('NEW_MESSAGE', 'New Message'), ('DISPUTE', 'Dispute')], max_length=40),
        ),
    ]
