# Generated by Django 6.0.3 on 2026-06-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_IN_PROGRESS', 'Booking In Progress'), ('BOOKING_COMPLETED', 'Booking Completed'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('NEW_MESSAGE', 'New Message'), ('DISPUTE', 'Dispute')], max_length=40),
        ),
    ]
