# Generated by Django 6.0.3 on 2026-04-26 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_flaggedmessagelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flaggedmessagelog',
            options={'ordering': ['-flagged_at']},
        ),
        migrations.AlterField(
            model_name='flaggedmessagelog',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
