# Generated by Django 6.0.3 on 2026-06-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_delivered_at_message_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedmessagelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20),
        ),
    ]
