# Generated by Django 6.0.3 on 2026-04-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('PHONEPE', 'PhonePe'), ('GOOGLE_PAY', 'Google Pay'), ('RAZORPAY', 'Razorpay'), ('CASH', 'Cash on Service')], default='UPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('VERIFIED', 'Verified'), ('RELEASED', 'Released'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20),
        ),
    ]
