# Generated by Django 6.0.3 on 2026-04-26 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_status'),
        ('payments', '0005_remove_wallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking'),
        ),
    ]
