# Generated by Django 6.0.3 on 2026-04-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='priority',
        ),
    ]
